#!/bin/bash

echo "🎓 Offline-First Attendance System - Demo Guide"
echo "=============================================="
echo ""

echo "📋 STEP-BY-STEP USAGE GUIDE"
echo "=========================="
echo ""

echo "1️⃣ SETUP (2 minutes)"
echo "-------------------"
echo "• Open terminal in project folder"
echo "• Run: cd attendance-app && npm install"
echo "• Run: cd ../backend && npm install"
echo ""

echo "2️⃣ START THE SYSTEM"
echo "------------------"
echo "Terminal 1 (Backend):"
echo "  cd backend"
echo "  npm start"
echo ""
echo "Terminal 2 (Frontend):"
echo "  cd attendance-app"
echo "  npm run dev"
echo ""

echo "3️⃣ OPEN IN BROWSER"
echo "-----------------"
echo "• Go to: http://localhost:5173"
echo "• You'll see the main screen with classes"
echo ""

echo "4️⃣ FIRST TIME USE"
echo "----------------"
echo "• System auto-loads demo data:"
echo "  📚 Computer Science 101 (5 students)"
echo "  📐 Mathematics 201 (3 students)"
echo ""

echo "5️⃣ TAKE ATTENDANCE (Daily Workflow)"
echo "----------------------------------"
echo "1. Click on 'Computer Science 101'"
echo "2. Click 'Take Attendance'"
echo "3. Select today's date (or any date)"
echo "4. Mark students: Present/Absent/Late"
echo "5. Click 'Save Attendance'"
echo ""

echo "6️⃣ TEST OFFLINE MODE"
echo "-------------------"
echo "• Disconnect internet"
echo "• Status shows 🔴 Offline"
echo "• Take attendance - works perfectly!"
echo "• Reconnect internet"
echo "• Status shows 🟢 Online"
echo "• Data syncs automatically!"
echo ""

echo "7️⃣ ADD YOUR OWN DATA"
echo "-------------------"
echo "• Click 'Classes' → 'Add Class'"
echo "• Enter: Class name, Subject, Teacher"
echo "• Select class → 'Add Student'"
echo "• Enter: Name, Roll Number, Email"
echo ""

echo "8️⃣ MOBILE USAGE"
echo "--------------"
echo "• Open in Chrome/Safari on phone"
echo "• Click 'Add to Home Screen'"
echo "• App icon appears on phone"
echo "• Works like native app!"
echo ""

echo "🎯 KEY FEATURES DEMO"
echo "==================="
echo ""
echo "✅ OFFLINE-FIRST:"
echo "   • Works without internet"
echo "   • Local storage (IndexedDB)"
echo "   • No server required for daily use"
echo ""
echo "✅ AUTO-SYNC:"
echo "   • Detects internet connection"
echo "   • Syncs data automatically"
echo "   • Green/Red status indicator"
echo ""
echo "✅ TEACHER-FRIENDLY:"
echo "   • Simple 3-click attendance"
echo "   • Large touch buttons"
echo "   • Mobile optimized"
echo ""
echo "✅ COLLEGE-READY:"
echo "   • Multiple classes support"
echo "   • Student management"
echo "   • Date-based tracking"
echo ""

echo "🚀 DEPLOYMENT OPTIONS"
echo "===================="
echo ""
echo "For Production Use:"
echo ""
echo "🌐 Cloud Deploy:"
echo "   • Frontend: Vercel/Netlify"
echo "   • Backend: Railway/Render"
echo "   • Run: ./deploy.sh"
echo ""
echo "🏠 Local Deploy:"
echo "   • Docker: docker-compose up"
echo "   • Manual: npm run build && serve"
echo ""
echo "📱 USB Deploy:"
echo "   • Build app, copy to USB"
echo "   • Run locally anywhere"
echo ""

echo "📞 SUPPORT & HELP"
echo "================"
echo ""
echo "❓ Having issues?"
echo "   • Check: http://localhost:3001/api/health"
echo "   • Clear browser cache"
echo "   • Try incognito mode"
echo ""
echo "📚 Full docs:"
echo "   • README.md - Overview"
echo "   • USAGE.md - Detailed guide"
echo "   • DEPLOYMENT.md - Deploy options"
echo ""

echo "🎉 READY TO TRANSFORM ATTENDANCE TAKING!"
echo "========================================="
echo ""
echo "Your offline-first attendance system is perfect for:"
echo "• Rural colleges with poor connectivity"
echo "• Field trips and outdoor activities"
echo "• Emergency situations"
echo "• Remote teaching scenarios"
echo ""
echo "🚀 Start using it now - no internet required!"